services:
  db:
    image: postgres:16.1
    container_name: postgresShareIt
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=shareIt
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck: #секция обеспечения того, что другие контейнеры (например, ваше приложение) не будут пытаться подключиться к базе данных, пока она не будет готова.
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10


